# Wakework config
wakewords: ["computer", "jarvis"]
#https://console.picovoice.ai/
picovice_access_key: "your_access_key"

RATE: 16000
language_code: "zh-CN"  # a BCP-47 language tag
microsoft_tts:
  subscription_key: "be533fxxxxxx"
  region: "eastasia"